name: HidePlayer
version: '${project.version}'
main: ga.pixelplayz.hideplayer.hideplayer.HidePlayer
load: STARTUP
authors: [ PixelPlayz ]
description: Hide Players By Clicking The Dye In Your Inventory
website: https://pixelplayz.ga
commands:
  hideplayer:
    description: hideplayer help for more info.
    permission: hideplayer
    permission-message: You Don't Have Permission
    usage: /pixelplayz <subcommand>
