name: HidePlayer
version: '1.3.0'
main: ga.pixelplayz.hideplayer.hideplayer.HidePlayer
load: STARTUP
softdepend: [ PlaceholderAPI ]
authors: [ PixelPlayz ]
description: Hide Players By Clicking The Dye In Your Inventory
website: https://pixelplayz.ga
commands:
  hideplayer:
    description: hideplayer help for more info.
    permission: hideplayer
    permission-message: You Don't Have Permission
    usage: /hideplayer <subcommand>
