name: Send Discord Embed on Release

on:
  release:
    types: [created]

jobs:
  send_discord_embed:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Embed
        uses: matthiaszarzecki/discord-webhook-action@v2
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Developer Bot
          content: |
            {
              "embeds": [
                {
                  "title": "${{ github.event.release.name }}",
                  "description": "${{ github.event.release.body }}",
                  "url": "${{ github.event.release.html_url }}",
                  "color": 00ff7b
                }
              ]
            }
