name: Send Discord Embed on Release

on:
  release:
    types: [created]

jobs:
  send_discord_embed:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Embed
        uses: actions/github-script@v3
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          script: |
            curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [
                {
                  "title": "${{ github.event.release.name }}",
                  "description": "${{ github.event.release.body }}",
                  "url": "${{ github.event.release.html_url }}",
                  "color": 3066993
                }
              ]
            }' \
            "$DISCORD_WEBHOOK_URL"
