name: Send Discord Embed for New Releases

on:
  pull_request:
  push:
    branches:
      - 'releases/*'

jobs:
  send-discord-embed:
    runs-on: ubuntu-latest

    steps:
    - name: Send Discord Embed
      uses: SebastiaanZ/github-status-embed-for-discord@v0.3.0
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: "New Release: ${{ github.event.release.name }}"
        description: "${{ github.event.release.body }}"
        url: "${{ github.event.release.html_url }}"
        color: "#00ff7b"
